import type React from 'react'

export type ProgramStatus = 'not_started' | 'active' | 'completed'
export type SubscriptionStatus = 'pending' | 'active' | 'failed' | 'cancelled'
export type UsageState = 'completed' | 'upcoming' | 'scheduled'
export type BrandStatus = 'active' | 'draft' | 'inactive'
export type ContactMethod = 'email' | 'phone'
export type AdminView = 'overview' | 'brands' | 'customers' | 'access'
export type ButtonVariant = 'primary' | 'outline' | 'ghost' | 'dark'
export type Brand = { id?: string; version?: number; slug: string; name: string; logo?: string; productImage?: string; productName: string; duration: number; schedule: number[]; usageTitle?: string; usageInstructions?: string; reorderUrl?: string; status: BrandStatus; theme: { primary: string; primaryHover: string; primaryText: string; secondary: string; highlight: string; highlightBorder: string } }
export type Customer = { id: string; firstName: string; email: string; phone?: string; orderNumber?: string; brandSlug: string; startDate: string; currentDay: number; programStatus: ProgramStatus; subscriptionStatus: SubscriptionStatus; completedDays: number[] }
export type AdminMetrics = { totalBrands: number; totalCustomers: number; activePrograms: number; activeSubscriptions: number }
export type ScheduleItem = { day: number; state: UsageState }
export type ProgramSummary = { currentDay: number; progressPercent: number; remainingDays: number; nextScheduledDay?: number; scheduledToday: boolean; low: boolean; complete: boolean }
export type CheckoutOutcome = 'processing' | 'cancelled' | 'failed' | 'success'
export type ErrorKind = 'invalid-link' | 'unavailable-brand' | 'network' | 'checkout-cancelled' | 'payment-failed' | 'missing-reorder'
export type ButtonProps = { children: React.ReactNode; variant?: ButtonVariant; href?: string; onClick?: () => void; type?: 'button' | 'submit'; disabled?: boolean }
export type BrandForm = { name: string; logo: string; primary: string; productName: string; duration: number; schedule: number[]; reorderUrl: string }
export type ValidationErrors = Partial<Record<'firstName' | 'contact' | 'orderNumber' | 'reorderUrl' | 'schedule', string>>
export type ThemeStyle = React.CSSProperties & Record<`--${string}`, string>
export type RouteProps = { params: Promise<{ brandSlug: string }> }
export type DetailRouteProps = { params: Promise<{ id: string }> }
export type CustomerShellProps = { children: React.ReactNode; brand: Brand }
export type AdminShellProps = { children: React.ReactNode; title: string; active?: AdminView }
export type MetricCardProps = { label: string; value: string; note: string }
export type BrandTheme = Brand['theme']
export type CustomerFormValues = { firstName: string; contact: string; method: ContactMethod; orderNumber: string }
export type ScheduleValidation = { valid: boolean; message?: string }
export type AccessLink = { brandSlug: string; url: string }
export type LinkDownloadFormat = 'png' | 'svg'
export type ErrorState = { kind: ErrorKind; title: string; message: string; action: string }
export type ErrorStateProps = { state: ErrorState; href?: string }
export type ReactNode = React.ReactNode
export type CSSProperties = React.CSSProperties
export type InputHTMLAttributes = React.InputHTMLAttributes<HTMLInputElement>
export type ButtonHTMLAttributes = React.ButtonHTMLAttributes<HTMLButtonElement>
export type AdminNavItem = { id: AdminView; label: string }
export type QAViewport = 375 | 390 | 430 | 768 | 1024 | 1440
export type TestResult = 'pass' | 'fail'
export type QAReport = { route: string; result: TestResult }[]
export type BrandEditorMode = 'create' | 'edit'
export type CheckoutState = 'connecting' | 'cancelled' | 'failed'
export type CopyStatus = 'idle' | 'copied' | 'error'
export type FormStatus = 'idle' | 'submitting' | 'success' | 'error'
export type EditableSchedule = { duration: number; days: number[] }
export type CustomerProgramContext = { brand: Brand; customer: Customer; summary: ProgramSummary }
export type ProgramDay = { day: number; label: string; state: UsageState }
export type AccessLinkState = { brandSlug: string; copied: boolean }
export type InputMode = 'email' | 'tel' | 'text'
export type BrandFormField = keyof BrandForm
export type CustomerField = keyof CustomerFormValues
export type StatusTone = 'success' | 'warning' | 'neutral' | 'error'
export type ProductState = 'available' | 'low' | 'complete'
export type ReorderState = 'available' | 'missing'
